using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace Syncromote
{
    
    public class Keyboard
    {
        public static int Convert(string key)
        {
            int index = ArraykeyName.IndexOf(key);
            
            return ArraykeyInt[index];
        }

        public static List<int> ArraykeyInt = new List<int>()
        {
            107,    //"add",
            8,    //"back",
            20,    //"capital",
            17,    //"control",
            46,    //"delete",
            111,    //"divide",
            40,    //"down",
            35,    //"end",
            27,    //"escape",
            112,    //"f1",
            113,    //"f2",
            114,    //"f3",
            115,    //"f4",
            116,    //"f5",
            117,    //"f6",
            118,    //"f7",
            119,    //"f8",
            120,    //"f9",
            121,    //"f10",
            122,    //"f11",
            123,    //"f12",
            36,    //"home",
            45,    //"insert",
            162,    //"leftcontrol",
            37,    //"left",
            160,    //"leftshift",
            106,    //"multiply",
            144,    //"numlock",
            96,    //"numpad0",
            97,    //"numpad1",
            98,    //"numpad2",
            99,    //"numpad3",
            100,    //"numpad4",
            101,    //"numpad5",
            102,    //"numpad6",
            103,    //"numpad7",
            104,    //"numpad8",
            105,    //"numpad9",
            168,    //"oem1",
            191,    //"oemquestion",
            192,    //"oem3",
            219,    //"oemopenbrackets",
            220,    //"oem5",
            221,    //"oem6",
            222,    //"oemquotes",
            188,    //"oemcomma",
            189,    //"oemminus",
            190,    //"oemperiod",
            187,    //"oemplus",
            13,    //"return",
            163,    //"rightcontol",
            39,    //"right",
            161,    //"rightshift",
            16,    //"shift",
            44,    //"snapshot",
            32,    //"space",
            109,    //"subtract",
            9,    //"tab",
            38,    //"up",
            48,    //"d0",
            49,    //"d1",
            50,    //"d2",
            51,    //"d3",
            52,    //"d4",
            53,    //"d5",
            54,    //"d6",
            55,    //"d7",
            56,    //"d8",
            57,    //"d9",
            65,    //"a",
            66,    //"b",
            67,    //"c",
            68,    //"d",
            69,    //"e",
            70,    //"f",
            71,    //"g",
            72,    //"h",
            73,    //"i",
            74,    //"j",
            75,    //"k",
            76,    //"l",
            77,    //"m",
            78,    //"n",
            79,    //"o",
            80,    //"p",
            81,    //"q",
            82,    //"r",
            83,    //"s",
            84,    //"t",
            85,    //"u",
            86,    //"v",
            87,    //"w",
            88,    //"x",
            89,    //"y",
            90    //"z"

        };
        public static List<string> ArraykeyName = new List<string>()
        {

            "add",
            "back",
            "capital",
            "control",
            "delete",
            "divide",
            "down",
            "end",
            "escape",
            "f1",
            "f2",
            "f3",
            "f4",
            "f5",
            "f6",
            "f7",
            "f8",
            "f9",
            "f10",
            "f11",
            "f12",
            "home",
            "insert",
            "leftcontrol",
            "left",
            "leftshift",
            "multiply",
            "numlock",
            "numpad0",
            "numpad1",
            "numpad2",
            "numpad3",
            "numpad4",
            "numpad5",
            "numpad6",
            "numpad7",
            "numpad8",
            "numpad9",
            "oem1",
            "oemquestion",
            "oem3",
            "oemopenbrackets",
            "oem5",
            "oem6",
            "oemquotes",
            "oemcomma",
            "oemminus",
            "oemperiod",
            "oemplus",
            "return",
            "rightcontol",
            "right",
            "rightshift",
            "shift",
            "snapshot",
            "space",
            "subtract",
            "tab",
            "up",
            "d0",
            "d1",
            "d2",
            "d3",
            "d4",
            "d5",
            "d6",
            "d7",
            "d8",
            "d9",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z"

        };
    }

}
